---
title: "assignment7"
author: "Subhasree Samanta"
date: "November 6, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(choroplethr)
library(choroplethrMaps)
library(ggthemes)
```

   
```{r, first dataset}
mortality <- read.csv("data/xmart.csv")

##Removing extra spaces
mortality[,3] <-gsub(" ","", mortality[,3]) 

##Renaming colnames for later
names(mortality) <- c("Country","Year","mm_ratio","births_attended")

##Extracting bounds
mortality$lower_bound <- str_split_fixed(str_extract(mortality[,3],"\\[[ 0-9 -]+\\]"), "-", 2)[,1]
mortality$upper_bound <- str_split_fixed(str_extract(mortality[,3],"\\[[ 0-9 -]+\\]"), "-", 2)[,2]

##Removing brackets
mortality$lower_bound <- as.integer(gsub("\\[", "", mortality$lower_bound))
mortality$upper_bound <- as.integer(gsub("\\]","", mortality$upper_bound))

##Removing bounds from col3
mortality[,3] <- as.integer(gsub("\\[[ 0-9 -]+\\]", "", mortality[,3]))
```

```{r, second dataset}
gni <- read.csv("data/WHS9_93.csv", skip=1, as.is = TRUE, check.names = FALSE)

##Removing extra spaces from & changing class of 2013 to integer
gni[,2] <-as.integer(gsub(" ","", gni[,2]))

##Tidying data: Using gather to have one entry per country per year
gni <- gni %>%
  gather(Year, income, 2:25)
```

```{r, merging data}

##Merging the two files, retaining only rows which have per capita income & maternal mortality or attended births
merged <- merge(gni,mortality) %>%
  filter(!is.na(income)) %>%
  filter(!is.na(mm_ratio) | !is.na(births_attended))

```


```{r, graphs}

## Plotting Maternal Mortality vs Income
plot1 <- merged %>%
  ggplot(aes(x=mm_ratio, y=income, color = Year)) + geom_point() + theme_minimal() + scale_color_ptol() + labs(title ="Maternal Mortality Versus Gross National Income", y="Gross National Income", x="Maternal Mortality Ratio", color = "Year")
plot1

## Plotting % of Attended Births vs Income
plot2 <- merged %>%
  ggplot(aes(x=births_attended, y=income, color = Year)) + geom_point() + theme_minimal() + scale_color_ptol() + labs(title ="Attended Births vs Gross National Income", y="Gross National Income", x="% of Attended Births", color = "Year")
plot2

##Want to identify some countries in the plots, will do later
```


```{r saving file}

## Saving merged & cleaned dataframe in data folder
write_csv(merged, "data/income.mortality.csv")
```


```{r, choropleth}
## Using aggregate to use most recent year for each country
choromerge <- merge(merged,aggregate(Year ~ Country, merged, max))

## Changing region names to lower to match region requirements for choropleth
choromerge[,1] <- str_to_lower(choromerge[,1])

##Checking which countries do not match the proper format
data(country.regions)
missing <- anti_join(choromerge, country.regions, by =c("Country" = "region"))

## Renaming some of the countries to follow the proper format as set by country.regions. Originally was renaming the exact entry, which is obviously problematic if the order is not the same in the dataframe. So doing this by str_replace_all. Still left with 19 countries in the missing dataset that I could not match with country.regions. 

choromerge$Country <- str_replace_all(choromerge$Country,"bahamas","the bahamas")
choromerge$Country <- str_replace_all(choromerge$Country,"viet nam","vietnam")
choromerge$Country <- str_replace_all(choromerge$Country,"united kingdom of great britain and northern ireland","united kingdom")
choromerge$Country <- str_replace_all(choromerge$Country,"iran \\(islamic republic of\\)","iran")
choromerge$Country <- str_replace_all(choromerge$Country,"venezuela \\(bolivarian republic of\\)", "venezuela")
choromerge$Country <- str_replace_all(choromerge$Country,"timor\\-leste","east timor")
choromerge$Country <- str_replace_all(choromerge$Country,"republic of moldova","moldova")
choromerge$Country <- str_replace_all(choromerge$Country,"the former yugoslav republic of macedonia","macedonia")
choromerge$Country <- str_replace_all(choromerge$Country,"republic of korea","south korea")
choromerge$Country <- str_replace_all(choromerge$Country,"russian federation","russia")
choromerge$Country <- str_replace_all(choromerge$Country,"lao people\\'s democratic republic","laos")
choromerge$Country <- str_replace_all(choromerge$Country,"bolivia \\(plurinational state of\\)","bolivia")
choromerge$Country <- str_replace_all(choromerge$Country,"brunei darussalam","brunei")
choromerge$Country <- str_replace_all(choromerge$Country,"cote d\\'ivoire","ivory coast")
choromerge$Country <- str_replace_all(choromerge$Country,"^congo","republic of congo")
choromerge$Country <- str_replace_all(choromerge$Country,"serbia","republic of serbia")
choromerge$Country <- str_replace_all(choromerge$Country,"guinea\\-bissau","guinea bissau")

##Choropleth
choromerge %>%
  dplyr::rename(value = mm_ratio, region = Country) %>%
  country_choropleth(title ="title")


```
